artifacts_root : artifacts

data_ingestion:
  root_dir: artificats/data_ingestion
  source_url : https://github.com/Axelblaze1O1/ml_project/raw/main/winequality-data.zip
  
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt